// Generated by ProtoGen, Version=2.4.1.521, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public static partial class Gcsystemmsgs {

  #region Extension registration
  public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
  }
  #endregion
  #region Static variables
  #endregion
  #region Descriptor
  public static pbd::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbd::FileDescriptor descriptor;
  
  static Gcsystemmsgs() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        "ChJnY3N5c3RlbW1zZ3MucHJvdG8q6hIKDEVHQ1N5c3RlbU1zZxITCg9rX0VH" + 
        "Q01zZ0ludmFsaWQQABIRCg1rX0VHQ01zZ011bHRpEAESGAoUa19FR0NNc2dH" + 
        "ZW5lcmljUmVwbHkQChIWChJrX0VHQ01zZ1N5c3RlbUJhc2UQMhIeChprX0VH" + 
        "Q01zZ0FjaGlldmVtZW50QXdhcmRlZBAzEhYKEmtfRUdDTXNnQ29uQ29tbWFu" + 
        "ZBA0EhgKFGtfRUdDTXNnU3RhcnRQbGF5aW5nEDUSFwoTa19FR0NNc2dTdG9w" + 
        "UGxheWluZxA2EhsKF2tfRUdDTXNnU3RhcnRHYW1lc2VydmVyEDcSGgoWa19F" + 
        "R0NNc2dTdG9wR2FtZXNlcnZlchA4EhUKEWtfRUdDTXNnV0dSZXF1ZXN0EDkS" + 
        "FgoSa19FR0NNc2dXR1Jlc3BvbnNlEDoSIgoea19FR0NNc2dHZXRVc2VyR2Ft" + 
        "ZVN0YXRzU2NoZW1hEDsSKgoma19FR0NNc2dHZXRVc2VyR2FtZVN0YXRzU2No" + 
        "ZW1hUmVzcG9uc2UQPBIiCh5rX0VHQ01zZ0dldFVzZXJTdGF0c0RFUFJFQ0FU" + 
        "RUQQPRIgChxrX0VHQ01zZ0dldFVzZXJTdGF0c1Jlc3BvbnNlED4SGgoWa19F" + 
        "R0NNc2dBcHBJbmZvVXBkYXRlZBA/EhsKF2tfRUdDTXNnVmFsaWRhdGVTZXNz" + 
        "aW9uEEASIwofa19FR0NNc2dWYWxpZGF0ZVNlc3Npb25SZXNwb25zZRBBEiIK" + 
        "HmtfRUdDTXNnTG9va3VwQWNjb3VudEZyb21JbnB1dBBCEhsKF2tfRUdDTXNn" + 
        "U2VuZEhUVFBSZXF1ZXN0EEMSIwofa19FR0NNc2dTZW5kSFRUUFJlcXVlc3RS" + 
        "ZXNwb25zZRBEEhgKFGtfRUdDTXNnUHJlVGVzdFNldHVwEEUSHwoba19FR0NN" + 
        "c2dSZWNvcmRTdXBwb3J0QWN0aW9uEEYSKAoka19FR0NNc2dHZXRBY2NvdW50" + 
        "RGV0YWlsc19ERVBSRUNBVEVEEEcSIgoea19FR0NNc2dSZWNlaXZlSW50ZXJB" + 
        "cHBNZXNzYWdlEEkSGAoUa19FR0NNc2dGaW5kQWNjb3VudHMQShIVChFrX0VH" + 
        "Q01zZ1Bvc3RBbGVydBBLEhcKE2tfRUdDTXNnR2V0TGljZW5zZXMQTBIYChRr" + 
        "X0VHQ01zZ0dldFVzZXJTdGF0cxBNEhcKE2tfRUdDTXNnR2V0Q29tbWFuZHMQ" + 
        "ThIfChtrX0VHQ01zZ0dldENvbW1hbmRzUmVzcG9uc2UQTxIaChZrX0VHQ01z" + 
        "Z0FkZEZyZWVMaWNlbnNlEFASIgoea19FR0NNc2dBZGRGcmVlTGljZW5zZVJl" + 
        "c3BvbnNlEFESGQoVa19FR0NNc2dHZXRJUExvY2F0aW9uEFISIQoda19FR0NN" + 
        "c2dHZXRJUExvY2F0aW9uUmVzcG9uc2UQUxIdChlrX0VHQ01zZ1N5c3RlbVN0" + 
        "YXRzU2NoZW1hEFQSGgoWa19FR0NNc2dHZXRTeXN0ZW1TdGF0cxBVEiIKHmtf" + 
        "RUdDTXNnR2V0U3lzdGVtU3RhdHNSZXNwb25zZRBWEhUKEWtfRUdDTXNnU2Vu" + 
        "ZEVtYWlsEFcSHQoZa19FR0NNc2dTZW5kRW1haWxSZXNwb25zZRBYEhwKGGtf" + 
        "RUdDTXNnR2V0RW1haWxUZW1wbGF0ZRBZEiQKIGtfRUdDTXNnR2V0RW1haWxU" + 
        "ZW1wbGF0ZVJlc3BvbnNlEFoSGgoWa19FR0NNc2dHcmFudEd1ZXN0UGFzcxBb" + 
        "EiIKHmtfRUdDTXNnR3JhbnRHdWVzdFBhc3NSZXNwb25zZRBcEh0KGWtfRUdD" + 
        "TXNnR2V0QWNjb3VudERldGFpbHMQXRIlCiFrX0VHQ01zZ0dldEFjY291bnRE" + 
        "ZXRhaWxzUmVzcG9uc2UQXhIbChdrX0VHQ01zZ0dldFBlcnNvbmFOYW1lcxBf" + 
        "EiMKH2tfRUdDTXNnR2V0UGVyc29uYU5hbWVzUmVzcG9uc2UQYBIYChRrX0VH" + 
        "Q01zZ011bHRpcGxleE1zZxBhEiQKIGtfRUdDTXNnV2ViQVBJUmVnaXN0ZXJJ" + 
        "bnRlcmZhY2VzEGUSHAoYa19FR0NNc2dXZWJBUElKb2JSZXF1ZXN0EGYSKAok" + 
        "a19FR0NNc2dXZWJBUElKb2JSZXF1ZXN0SHR0cFJlc3BvbnNlEGgSKwona19F" + 
        "R0NNc2dXZWJBUElKb2JSZXF1ZXN0Rm9yd2FyZFJlc3BvbnNlEGkSGQoUa19F" + 
        "R0NNc2dNZW1DYWNoZWRHZXQQyAESIQoca19FR0NNc2dNZW1DYWNoZWRHZXRS" + 
        "ZXNwb25zZRDJARIZChRrX0VHQ01zZ01lbUNhY2hlZFNldBDKARIcChdrX0VH" + 
        "Q01zZ01lbUNhY2hlZERlbGV0ZRDLARIbChZrX0VHQ01zZ01lbUNhY2hlZFN0" + 
        "YXRzEMwBEiMKHmtfRUdDTXNnTWVtQ2FjaGVkU3RhdHNSZXNwb25zZRDNARIf" + 
        "ChprX0VHQ01zZ01hc3RlclNldERpcmVjdG9yeRDcARInCiJrX0VHQ01zZ01h" + 
        "c3RlclNldERpcmVjdG9yeVJlc3BvbnNlEN0BEiMKHmtfRUdDTXNnTWFzdGVy" + 
        "U2V0V2ViQVBJUm91dGluZxDeARIrCiZrX0VHQ01zZ01hc3RlclNldFdlYkFQ" + 
        "SVJvdXRpbmdSZXNwb25zZRDfARImCiFrX0VHQ01zZ01hc3RlclNldENsaWVu" + 
        "dE1zZ1JvdXRpbmcQ4AESLgopa19FR0NNc2dNYXN0ZXJTZXRDbGllbnRNc2dS" + 
        "b3V0aW5nUmVzcG9uc2UQ4QESFwoSa19FR0NNc2dTZXRPcHRpb25zEOIBEh8K" + 
        "GmtfRUdDTXNnU2V0T3B0aW9uc1Jlc3BvbnNlEOMBEhgKE2tfRUdDTXNnU3lz" + 
        "dGVtQmFzZTIQ9AMSIwoea19FR0NNc2dHZXRQdXJjaGFzZVRydXN0U3RhdHVz" + 
        "EPUDEisKJmtfRUdDTXNnR2V0UHVyY2hhc2VUcnVzdFN0YXR1c1Jlc3BvbnNl" + 
        "EPYDEhoKFWtfRUdDTXNnVXBkYXRlU2Vzc2lvbhD3AxIlCiBrX0VHQ01zZ0dD" + 
        "QWNjb3VudFZhY1N0YXR1c0NoYW5nZRD4AxIcChdrX0VHQ01zZ0NoZWNrRnJp" + 
        "ZW5kc2hpcBD5AxIkCh9rX0VHQ01zZ0NoZWNrRnJpZW5kc2hpcFJlc3BvbnNl" + 
        "EPoDKu8BCgZFU09Nc2cSEwoPa19FU09Nc2dfQ3JlYXRlEBUSEwoPa19FU09N" + 
        "c2dfVXBkYXRlEBYSFAoQa19FU09Nc2dfRGVzdHJveRAXEhwKGGtfRVNPTXNn" + 
        "X0NhY2hlU3Vic2NyaWJlZBAYEh4KGmtfRVNPTXNnX0NhY2hlVW5zdWJzY3Jp" + 
        "YmVkEBkSGwoXa19FU09Nc2dfVXBkYXRlTXVsdGlwbGUQGhIjCh9rX0VTT01z" + 
        "Z19DYWNoZVN1YnNjcmlwdGlvbkNoZWNrEBsSJQoha19FU09Nc2dfQ2FjaGVT" + 
        "dWJzY3JpcHRpb25SZWZyZXNoEBwqyAEKEEVHQ0Jhc2VDbGllbnRNc2cSGgoV" + 
        "a19FTXNnR0NDbGllbnRXZWxjb21lEKQfEhoKFWtfRU1zZ0dDU2VydmVyV2Vs" + 
        "Y29tZRClHxIYChNrX0VNc2dHQ0NsaWVudEhlbGxvEKYfEhgKE2tfRU1zZ0dD" + 
        "U2VydmVySGVsbG8Qpx8SIwoea19FTXNnR0NDbGllbnRDb25uZWN0aW9uU3Rh" + 
        "dHVzEKkfEiMKHmtfRU1zZ0dDU2VydmVyQ29ubmVjdGlvblN0YXR1cxCqHyqJ" + 
        "AgoKRUdDVG9HQ01zZxIaChVrX0VHQ1RvR0NNc2dNYXN0ZXJBY2sQlgESIgod" + 
        "a19FR0NUb0dDTXNnTWFzdGVyQWNrUmVzcG9uc2UQlwESFwoSa19FR0NUb0dD" + 
        "TXNnUm91dGVkEJgBEhwKF2tfRUdDVG9HQ01zZ1JvdXRlZFJlcGx5EJkBEhoK" + 
        "FWtfRU1zZ1VwZGF0ZVNlc3Npb25JUBCaARIbChZrX0VNc2dSZXF1ZXN0U2Vz" + 
        "c2lvbklQEJsBEiMKHmtfRU1zZ1JlcXVlc3RTZXNzaW9uSVBSZXNwb25zZRCc" + 
        "ARImCiFrX0VHQ1RvR0NNc2dNYXN0ZXJTdGFydHVwQ29tcGxldGUQnQE=");
    pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
      descriptor = root;
      return null;
    };
    pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
        new pbd::FileDescriptor[] {
        }, assigner);
  }
  #endregion
  
}
#region Enums
public enum EGCSystemMsg {
  k_EGCMsgInvalid = 0,
  k_EGCMsgMulti = 1,
  k_EGCMsgGenericReply = 10,
  k_EGCMsgSystemBase = 50,
  k_EGCMsgAchievementAwarded = 51,
  k_EGCMsgConCommand = 52,
  k_EGCMsgStartPlaying = 53,
  k_EGCMsgStopPlaying = 54,
  k_EGCMsgStartGameserver = 55,
  k_EGCMsgStopGameserver = 56,
  k_EGCMsgWGRequest = 57,
  k_EGCMsgWGResponse = 58,
  k_EGCMsgGetUserGameStatsSchema = 59,
  k_EGCMsgGetUserGameStatsSchemaResponse = 60,
  k_EGCMsgGetUserStatsDEPRECATED = 61,
  k_EGCMsgGetUserStatsResponse = 62,
  k_EGCMsgAppInfoUpdated = 63,
  k_EGCMsgValidateSession = 64,
  k_EGCMsgValidateSessionResponse = 65,
  k_EGCMsgLookupAccountFromInput = 66,
  k_EGCMsgSendHTTPRequest = 67,
  k_EGCMsgSendHTTPRequestResponse = 68,
  k_EGCMsgPreTestSetup = 69,
  k_EGCMsgRecordSupportAction = 70,
  k_EGCMsgGetAccountDetails_DEPRECATED = 71,
  k_EGCMsgReceiveInterAppMessage = 73,
  k_EGCMsgFindAccounts = 74,
  k_EGCMsgPostAlert = 75,
  k_EGCMsgGetLicenses = 76,
  k_EGCMsgGetUserStats = 77,
  k_EGCMsgGetCommands = 78,
  k_EGCMsgGetCommandsResponse = 79,
  k_EGCMsgAddFreeLicense = 80,
  k_EGCMsgAddFreeLicenseResponse = 81,
  k_EGCMsgGetIPLocation = 82,
  k_EGCMsgGetIPLocationResponse = 83,
  k_EGCMsgSystemStatsSchema = 84,
  k_EGCMsgGetSystemStats = 85,
  k_EGCMsgGetSystemStatsResponse = 86,
  k_EGCMsgSendEmail = 87,
  k_EGCMsgSendEmailResponse = 88,
  k_EGCMsgGetEmailTemplate = 89,
  k_EGCMsgGetEmailTemplateResponse = 90,
  k_EGCMsgGrantGuestPass = 91,
  k_EGCMsgGrantGuestPassResponse = 92,
  k_EGCMsgGetAccountDetails = 93,
  k_EGCMsgGetAccountDetailsResponse = 94,
  k_EGCMsgGetPersonaNames = 95,
  k_EGCMsgGetPersonaNamesResponse = 96,
  k_EGCMsgMultiplexMsg = 97,
  k_EGCMsgWebAPIRegisterInterfaces = 101,
  k_EGCMsgWebAPIJobRequest = 102,
  k_EGCMsgWebAPIJobRequestHttpResponse = 104,
  k_EGCMsgWebAPIJobRequestForwardResponse = 105,
  k_EGCMsgMemCachedGet = 200,
  k_EGCMsgMemCachedGetResponse = 201,
  k_EGCMsgMemCachedSet = 202,
  k_EGCMsgMemCachedDelete = 203,
  k_EGCMsgMemCachedStats = 204,
  k_EGCMsgMemCachedStatsResponse = 205,
  k_EGCMsgMasterSetDirectory = 220,
  k_EGCMsgMasterSetDirectoryResponse = 221,
  k_EGCMsgMasterSetWebAPIRouting = 222,
  k_EGCMsgMasterSetWebAPIRoutingResponse = 223,
  k_EGCMsgMasterSetClientMsgRouting = 224,
  k_EGCMsgMasterSetClientMsgRoutingResponse = 225,
  k_EGCMsgSetOptions = 226,
  k_EGCMsgSetOptionsResponse = 227,
  k_EGCMsgSystemBase2 = 500,
  k_EGCMsgGetPurchaseTrustStatus = 501,
  k_EGCMsgGetPurchaseTrustStatusResponse = 502,
  k_EGCMsgUpdateSession = 503,
  k_EGCMsgGCAccountVacStatusChange = 504,
  k_EGCMsgCheckFriendship = 505,
  k_EGCMsgCheckFriendshipResponse = 506,
}

public enum ESOMsg {
  k_ESOMsg_Create = 21,
  k_ESOMsg_Update = 22,
  k_ESOMsg_Destroy = 23,
  k_ESOMsg_CacheSubscribed = 24,
  k_ESOMsg_CacheUnsubscribed = 25,
  k_ESOMsg_UpdateMultiple = 26,
  k_ESOMsg_CacheSubscriptionCheck = 27,
  k_ESOMsg_CacheSubscriptionRefresh = 28,
}

public enum EGCBaseClientMsg {
  k_EMsgGCClientWelcome = 4004,
  k_EMsgGCServerWelcome = 4005,
  k_EMsgGCClientHello = 4006,
  k_EMsgGCServerHello = 4007,
  k_EMsgGCClientConnectionStatus = 4009,
  k_EMsgGCServerConnectionStatus = 4010,
}

public enum EGCToGCMsg {
  k_EGCToGCMsgMasterAck = 150,
  k_EGCToGCMsgMasterAckResponse = 151,
  k_EGCToGCMsgRouted = 152,
  k_EGCToGCMsgRoutedReply = 153,
  k_EMsgUpdateSessionIP = 154,
  k_EMsgRequestSessionIP = 155,
  k_EMsgRequestSessionIPResponse = 156,
  k_EGCToGCMsgMasterStartupComplete = 157,
}

#endregion


#endregion Designer generated code
